%% Analyse tlog data
% Doesn't work well at the moment
close all
clear all
clc


load('./data/bwb_flight.tlog.mat')

%% Wind data
figure(); clf; hold all; 
subplot(2,1,1); hold all; ...
    plot(((speed_mavlink_wind_t(:,1)-speed_mavlink_wind_t(1,1)))*24*60*60,speed_mavlink_wind_t(:,2));...
    plot((speed_z_mavlink_wind_t(:,1)-speed_z_mavlink_wind_t(1,1))*24*60*60,speed_z_mavlink_wind_t(:,2));...
    ylabel('Wind Speed [ m/s ]'); legend('Horizontal','Vertical');
subplot(2,1,2); hold all;...
    plot((direction_mavlink_wind_t(:,1)-direction_mavlink_wind_t(1,1))*24*60*60,unwrap_180(direction_mavlink_wind_t(:,2)));...
    ylabel('Wind Direction [ deg ]'); xlabel('Time [ s ]');

%% Airspeed
figure(); clf; hold all;
subplot(2,1,1); hold all; ...
     plot(((airspeed_mavlink_vfr_hud_t(:,1)-airspeed_mavlink_vfr_hud_t(1,1)))*24*60*60,airspeed_mavlink_vfr_hud_t(:,2));...
     plot(((groundspeed_mavlink_vfr_hud_t(:,1)-groundspeed_mavlink_vfr_hud_t(1,1)))*24*60*60,groundspeed_mavlink_vfr_hud_t(:,2));...
     ylabel('Speed [ m/s ]'); legend('Air','Ground');

%% Climb rate
% figure(); clf; hold all;
% subplot(2,1,1); hold all; ...
%      plot(((climb_mavlink_vfr_hud_t(:,1)-climb_mavlink_vfr_hud_t(1,1)))*24*60*60,climb_mavlink_vfr_hud_t(:,2));...
%     ylabel('Climb Rate [ m/s ]');

%% Heading
% heading_mavlink_vfr_hud_t

%% Current
figure(); clf; hold all;
subplot(2,1,1); hold all; ...
     plot(((airspeed_mavlink_vfr_hud_t(:,1)-airspeed_mavlink_vfr_hud_t(1,1)))*24*60*60,airspeed_mavlink_vfr_hud_t(:,2));...
     plot(((groundspeed_mavlink_vfr_hud_t(:,1)-groundspeed_mavlink_vfr_hud_t(1,1)))*24*60*60,groundspeed_mavlink_vfr_hud_t(:,2));...
     ylabel('Speed [ m/s ]'); legend('Air','Ground');
subplot(2,1,2); hold all; ...
    power = current_battery_mavlink_sys_status_t(:,2)/100 .* voltage_battery_mavlink_sys_status_t(:,2)/1000;...
     plot(((current_battery_mavlink_sys_status_t(:,1)-current_battery_mavlink_sys_status_t(1,1)))*24*60*60,power);...
     xlabel('Time [ s ]'); ylabel('Power [ W ]');
    
